In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [5]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv", encoding="latin-1")

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
X = data["text"]
y = data["label"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## Data Preprocessing

In [11]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [13]:
import re

In [20]:
text = X_train.iloc[0]
re.sub("<.*?>", "", text)
cleaned_X_train = [re.sub("<.*?>", '', text) for text in X_train]
print(cleaned_X_train)

['When you are ready pls call into ops and they will connect u to blair.', "From=3AMr=2EKabir Bello=2E E-mail=3A Kabir=40she=2EcomTel=3A+66-1-4919460=2EAttention=3AThe Managing DirectorBefore I proceed=2C may I humbly introduce myself to your good self=2C My Name is Mr=2EKabir Bello=2C an Iraqi refugee =2Cmy Father was until recently=2C one of the personal aid to the president of Iraq who was formerly overthrown out of power during the War in My Country which took many life =2E Prior to this last serious crisis that is still ravaging in my country=2C which recently led to misfortune of our government and my late Father's position as the personal aid to the president=2C we were able to come over here in Thailand with my mother for investment =2Cwe inherited the sum of US$16 Million=2E The funds were originally gotten from my late Father's proceeds=2E My late father was able to safe guard the fund with a very good diplomatic contact from my Country to Thailand which make us to come here to plan our life=2E But all is about life and death I witnessed another tragedy which could have taken my own life in Thailand here but I feel this is not the time=2C It started on 26th of December here in Phuket another disaster occurred here named=28 TSUNAMI=29 which as well took the life of my mother and up till now her body are yet to to be found=2C I am the only surviving person in my Family now=2EI have decided to contact you because I am interested in investing in your country =2E Please kindly guide and assist me in making the right investment as every thing regarding technical and logistics details is worked out and ascertained to our respective satisfaction=2E In view of your participation=2C I am ready to give you a good negotiable percentage for your assistance=2C or better still commit it into viable Joint venture projects=2C be assured that you stand no risk of any kind as the funds belong to me as the only surviving son=2E As soon as I get your consent=2C I will quickly move this fund to your country for investment =2E However=2C upon your acceptance to work as my partner=2C you can contact me with my private telephone number or e-mail for more details=2EI strongly believe that associating with you to embark on this and other business ventures will derive a huge success here after=2C please include you private contact telephone number and private e-mail when replying=2EYours Sincerely=2EMr=2EKabir Bello=2E", "Ok. Let's do him Mcguinness and Gates and F-Fasi. Probably from the office to ensure a good connection.", '03-23-2010.doc; Strategic Dialogue Press Clips March 24 2010.doc; Strategic DialoguePress Clips 03-25-2010.doc; Strategic Dialogue Press Clips 03-26-2010.doc; StrategicDialogue Press Clips 03-27-2010.doc; Strategic Dialogue Press Clips 03-28-2010.doc;Strategic Dialogue Press Clips 03-29-2010.doc; Strategic Dialogue Press Clips03-30-2010.doc; Strategic Dialogue Press Clips 03-31-2010.docFYI generally positive coverage.im', "From=3A Mr=2E HOFFMAN  BancoleyAccra=2C Ghana=2EAttn =3AI got your contact during my search for a reliable=2Chonest and atrust worth person to entrust this huge transfer project with=2EMy name is Mr=2EHoffman Bancoley=2C manager of the above namedfinancial institution=2EI am a Ghanaian married with two kids=2EI am writing to solicit your assistance in the transfer of$4=2C550=2E000 U=2ES Dollars=2EThis fund is the excess of what my branch in which I am the managermade as profit during the 2004 financial year=2E I have already submittedannual report for that year to my head office here in Accra as I havewatched with keen interest as they will never know of this excess=2EI have since=2C placed this amount of $4=2C550=2E000 U=2ES Dollars onan Escrow Coded account without a beneficiary =28anonymous=29 to avoid trace=2EAs an officer of the bank=2C I cannot be directly connected to this money thusI am impelled to request for your assistance to receive this money into yourbank account on my behalf=2EI intend to part 30% of this fund to you while 70% shall be for me=2E I do needto stress that there are practically no risk involved in this=2E It's going to bea bank-to-bank transfer=2E All I need from you is to stand as the originaldepositor of this fund so that the fund can be transferred to your account=2EIf you accept this offer=2C I will appreciate your timely response to myprivate email=2E=2E=2E=2E=2Emancoleyghanac=40latinmail=2Ecom Mr=2E Hoffman  Bancoley", 'Marshall Capricia P Friday May 28 2010 5:03 PMHÃ¢Â\x96Â\xa0', 'Thanks Madame Secretary --Kagan also had an unusually supportive piece on Friday that prominently mentioned your role on AsiaHe built Singapore from nothing and his book is pretty damn inspirational on that front.I leave for Asia early Monday and will check in from the road. Thanks and best Kurt', 'FYI', 'Cherie BlairSunday May 24 2009 6:35 AMH; hr15@mycingular.blackberry.netFW: FW: confidentialDear Hilary it seems if you suggest a day she will come to you. DO you want to let me know and I will go back to them', 'Dear Friend,My Compliment to you,I guess this letter may come to you as a surprise since I had no previous correspondence with you.I am sending you this mail on behalf of the chairman tender board of Independent National Electoral Commission (INEC) MR. SETTLEY DAZE. We got your contact in our search for a reliable person to handle a very confidential transaction involving the transfer of Forty Nine Million, Five Hundred Thosand United States Dollars US$49.5Million.The above fund is not connected with arms, drugs or money laundering. It is the product of an over invoiced Contract awarded in 2001 by INEC to a foreign company for the construction of high rise estate in the federal capital territory.The contract has long been executed and payment of the actual contract amount has been paid to the foreign contractor leaving the balance, which my colleague and I now want to transfer out of Nigeria into a reliable foreign account for our personal use.As civil servants we are not allowed to run foreign accounts. Hence we have chosen you to front and support us as the beneficiary to be paid. If you are interested in the proposal kindly get back to me by sending me your letter of acceptance along with your direct telephone and fax numbers, For your support and partnership, please reply me to negotiate your fees or the percentage you wish to be paid when the funds arrive your bank account. Further details about this transaction will be discussed in the subsequent correspondence. Note also that the particular nature of your business is irrelevant to this transaction and all local contacts and arrangements are in place for a smooth and successful conclusion of this transaction.Be informed that we are aware of the way email proposals of this type are being sent from this part of africa and as regards that, you should please treat this with utmost attention knowing fully well that you cannot and will not be compelled to assist us if you are not disposed to.Contact me via my email account or you also reach me on this email account she_rashabubakar@yahoo.com with your contact telephone and fax numbers on response, I will call you for a discussion.Thank you as I await your response.Sincerely,Dr. Rasheed S. Abubakar. ', '\ttpowers@lyon.k12.nv.us, rrichmond@lyon.k12.nv.us,\tsreiger@lyon.k12.nv.us, srieger@lyon.k12.nv.us,\ttromer@lyon.k12.nv.us, jruff@lyon.k12.nv.us, gsuarez@lyon.k12.nv.us,\tmtaylor@lyon.k12.nv.us, jvalenzuela@lyon.k12.nv.us,\tavanparys@lyon.k12.nv.us, rwilson@lyon.k12.nv.us,\tdwinans@lyon.k12.nv.us, emcservice@utility.org,\tmajordomo@world.std.com, jshandor@tgc.com, R@M,\t1070986800.0122@hypermail.dumm, dhart@nsf.gov,\tdhart@harbourrocks.com.au, dhart@ecs.giswave.com, dhart@ecps.us,\tedonoghue@saintpetersuh.com, jsignor@e-z.net, cory@dhart.com,\tdwaters@hanover.k12.va.us, rdeel@hanover.k12.va.us,\tcarol@caslet22.freeserve.co.uk, eliz.purves@btinternet.com,\tbarbara@newbattle.freeserve.co.uk, roneil@xtra.co.nz,\tyvonne.burder@ntlworld.com, dubhda@supanet.com,\tdaymargaretstan@aol.com, galvez@c-zone.net, paul.wickers@nep.co.uk,\tve7ibv@hotmail.com, dvchis@bigpond.net.au, lyndaw@optusnet.com.au,\tmhjmitz@aol.com, garrylawes@hotmail.com, charliebrown99@talk21.com,', 'French.docx; Final Communique Portuguese.docx;FinalCommuniqueCreole_Revision.docxFyi', "Dear  freind=2CThis is a proposal in context but actually an appealsolicitingfor your unreserved assistance in carrying out  anurgenttransaction requiring maximum confidence=2E Though thisapproachappears desperate=2C I can assure you that whateverquestions you would need to ask or any other thing youwillneed to know regarding this proposal will beadequatelyanswered to give you a clearer understanding of it=2C soas toarrive at a successful conclusion=2EMy name is Dr Pimentel luisa Estrada=2C wife of HisExcellencyJoseph Estrada=2C former President of The Philippines=2EMy husbandwas impeached from office by a backed uprisingof massdemonstrators and the Senate and is presently in jailontrumped up charges of corruption=2C embezzlement=2C andthe mysteriouscharge of economy plunder which might lead to deathsentence=2EThe present government is forcing my husband out ofManila toavoid demonstration by his supporters=2E As God would have it=2Ci realised somereasonable amount of money from various deals that Isuccessfully executed=2C during my husband's regime asPresidentof Philippines=2E I have plans to invest this money formychildren's future on real estate and industrialproduction=2EI have carefully moved out these funds =28US$30million=29=2C beforemy husband was impeached to an offshore DepositCompanyin the European Union=2E My husband is not aware of thisbecauseI want to handle it secretly for obvious resons=2E>From past experiences=2C many people I had regarded asclosefriends has capitalized on my family's travail to runaway withmy money=2E In order to avert this negative development=2CMy son and i now seek your permission toallow myattorney do a CHANGE OF OWNERSHIP=2FREASSIGNMENT OFCREDIT of the statedfunds from the deposit company to your name=2C so thatthe funds =28US$30million=29 would be released to you asthe newowner =28on my familys behalf=29=2EI am writing because when I deposited the money in thedepositcompany=2C I told them that it belonged to a foreignbusinesspartner and my present position will not allow me toclaim thefunds=2E Consequently=2C I will present you as the ownerof thefunds in the Deposit Company so you can be able toclaim the funds=2E Thisis simple=2E I will like you to provide immediately=3B1=2E Full names2=2E Contact address3=2E Telephone and fax numbersOnce I receive this information=2C I will prepare thenecessarydocuments that will put you in place as the new ownerof thefunds=2EThe money will then be released to your custody by theDepositCompany=2C for us to share in the ratio of 70% for usand 30% foryou=2E There is no risk at all as all the paperwork forthistransaction will be done by the solicitor and thiswillguarantees the successful execution of thistransaction=2EIf you are interested=2C please reply immediately via myemailaddress=2E Upon your response=2C I shall then introduceyou to myson who is going to liaise with you for furtherexplanation thatwill help you understand the transaction=2ENo doubt this proposal will make you apprehensive=2Cplease weemploy you to observe utmost confidentiality and restassuredthat this transaction would be most profitable forboth of usbecause we shall require your assistance to invest ourshare inyour country =28buying of properties like houses=2C hotelsetc=29=2EThis is why your urgent action and response is ofpriority toenable us concluded this transaction in a timely andprofessionalmanner=2E=2EPlease reply me  AT the email address below =2C mypersonal email =2CEmail =3A drluisaestrada1=40philippines=2EtoFor utmost confidentiality sake=2EI do expect to hear from you shortly =2C but if you arenot interested =2Cplease accept my unreserved apology=2E Thanks and regardsDr=2E=28Mrs=2E=29 Luisa Estrada", 'FYI', "I talked to Shelly and she is grateful for your call. She has a new phone and hasn't set up her VM yet.", 'tent/advdetail.jsp?advid=3Dadvrss&advsvc=3Dadvcomplete&TARGETCODE=3DFR_fo=otermail_link">  CaraMail, le seul webmail =E0 vous offrir des= fils d\'info RSS sans aucun logiciel =E0 installer!--=_NextPart_Lycos_229741953391973_ID--', 'Of course!Lona ValmoroSpecial Assistant to the Secretary of State B6', 'We have remarks for you. I recommend calls to PR and MM before you do the press.', 'Dear Friend,Attention Please.Sorry to disturb you. I am Dr Idris Ali, the Director in charge of Auditing and Accounting section of AFRICAN DEVELOPMENT BANK (A.D.B) Ouagadougou Burkina-faso West Africa. With due respect and regard. I have decided to contact you on a business transaction that will be very beneficial to both of us at the end of the transaction .During our investigation and auditing in this bank, my department came across a very huge sum of money belonging to a deceased person who died in a plane crash and the fund has been dormant in his account with this Bank without any claim of the fund in our custody either from his family or relation before our discovery to this development.The said amount was U.S 7.5M (Seven Million,Five Hundred Thousand United States Dollars). As it may interest you to know, I got your impressive information through internet directory . Meanwhile all the whole arrangement to put claim over this fund as the bonafide next of kin to the deceased, get the required approval and transfer this money to a foreign account has been put in place and directives and needed information will be relayed to you as soon as you indicate your interest and willingness to assist, and also benefit your self to this great business opportunity.In fact I could have done this deal alone but because of my position in this country as a civil servant(A Banker),we are not allowed to operate a foreign account and would eventually raise an eye brow on my side during the time of transfer because I work in this bank. This is the actual reason why it will require a second party or fellow who will forward claims as the next of kin with affidavit of trust of oath to the Bank and also present a foreign account where he will need the money to be re-transferred into on his request as it may be after due verification and clarification by the correspondent branch of the bank where the whole money will be remitted from to your own designation bank account.I will not fail to inform you that this transaction is 100% risk free.On smooth conclusion of this transaction, you will be entitled to 30% of the total sum as gratification, while 10% will be set aside to take care of expenses that may arise during the time of transfer and also telephone and internet bills, while 60% will be for me and my coleagues. Please, you have been adviced to keep "Top Secret" as I am still in service and intend to retire from service after we conclude this deal with you.I will be monitoring the whole situation here in this bank until you confirm the money in your account and ask me to come down to your country for subsequent sharing of the fund according to percentages previously indicated and further investment, either in your country or any country you advice us to invest in. All other necessary vital nformation will be sent to you when I hear from you.I look forward to receive your phone and fax numbers for easy communication,Yours faithfully,Dr Idris Ali._________________________________________________________________Windows Live Messenger : venez tester la version bÃ¯Â¿Â½ta ! http://www.ideas.live.com/programpage.aspx?versionId=5d21c51a-b161-4314-9b0e-4911fb2b2e6d', "CHRIST BETHEL HOSPITAL11 RUE ABOBOTE,ABIDJANIVORY COAST  Dearest Beloved ,  I am SISTER ANITA ADAMS JOHNSON from Ivory Coast. I was married to Late Chief Adams Johnson who was a contractor with the government of Cote D'Ivoire before he died after few days in the hospital owing to high blood presure.&nbsp;When my late husband was alive he deposited the sum of $8.700 Million with a Bank in Cote D lvoire for investment outside west Africa in&nbsp; fixed account stating the the fund will be transfered into an account of his foriegn partner .Presently this money is still in the custody of the Bank here in Cote DIvoire.And I want communicate to the bank that you are my late husband foriegn business partner based on your sincere accptance to assist.My Doctor told me that it is very likely i will die within the next 3 months due to A Blood cancer {LUCAMIA}.&nbsp;Hence my late husband brother who would have inherited the fund is responsible for his death and&nbsp; i vowed not to associate with him for my dear life.&nbsp;I have decided to donate the money for charity to A GOD FEARING PERSON like you since i do not have a child to inherit it and it better i do not die leaving the money here without it reaching the poor and the less privilaged ones in the society.OR I ALLOW THE FUND TO BE IN THE BANK.  As soon as the fund is transfered into your reciving cordinate,you will take 30 percent of the total amount and use the balance of the fund as stated below:  a).BUILDING A HOUSE FOR LORD.b).DONATION TO MOTHELESS BABY HOMESc).TRAINING CENTER FOR THE DEAF AND DUMP.  As soon as I receive your reply I shall tell my bank to transfer themoney to you so that if i die now i know where i am going.And i have nothing to regret since i have fulfiled my heart desire .  PLEASE FEEL FREE TO CONTACT ME&nbsp; for more information and details you might need from me.  God bless you.YOURS SINCERELY,SISTER ANITA ADAMS JOHNSON.", ">From The Desk of Mr.Mustapha SallehManager National Bank of Dubai Abu Dhabi branch Dubai United Arab Emirate (U.A.E.)Email;mr_mustaphasalleh@yahoo.comDear, I am Mr. Mustapha Salleh Manager National Bank of Dubai Abu Dhabi branch, I =have urgent and very confidential business proposition foryou. A British Oil =consultant and contractor with the Kruger Gold Company, Mr. Raymond Beck made =a numbered time (Fixed) Deposit for twelve calendar months, valued at US$25m =(Twenty Five Million United States American Dollars). in my branch. Upon maturity,I sent a routine notification to his forwarding address but got =no reply.After a month, we sent a reminder and finally we discovered from his =contract employers, the Kruger Gold Company that Mr. Raymond Beck died in a =plane crash along with his wife Mr. and Mrs. Raymond Beck died in a plan =crash along with his wife in Egypt Air Flight 990,1999 aircrash (for more information about this crash and person you can contact this =websiteSince we got this information about his death and on further investigation, I =found out that he died without making a WILL, and all attempts to trace his =next of kin was fruitless. I therefore made further investigation and =discovered that Mr. Raymond Beck did not declare any kin or relations in all =his official documents, including his Bank Deposit paperwork in my Bank. This sum of US$25m (Twenty Five Million United States American Dollars).is =still sitting in my Bank and the interest is being rolled over with the =principal sum at the end of each year. No one will ever come forward to claim =it. According to Laws of United Arab Emirates, at the expiration of 7 (seven) =years, the money will revert to the ownership of the (U.A.E) Government if =nobody applies to claim the fund.Consequently, my proposal is that I will like you as a foreigner to stand in =as the next of kin to Mr. Raymond Beck so that the fruits of this old man's =labor will not get into the hands of some corrupt government officials. This =is simple, I will like you to provide immediately your full names and address =so that the attorney will prepare the necessary documents and affidavits that =will put you in place as the next of kin. We shall employ the services of an attorney for drafting and notarization of 

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [32]:
cleaned_X_train = [re.sub(r'[^a-zA-Z0-9\s]','',text)for text in cleaned_X_train]
cleaned_X_train = [re.sub(r'[0-9]', '', text) for text in cleaned_X_train]
cleaned_X_train = [re.sub(r'\b[a-zA-Z]\b', '', text) for text in cleaned_X_train]
cleaned_X_train = [re.sub(r'^[a-zA-Z]\s+', '',text) for text in cleaned_X_train]
cleaned_X_train = [re.sub(r'\s+', ' ', text)for text in cleaned_X_train]
cleaned_X_train = [re.sub(r'^','', text) for text in cleaned_X_train]
cleaned_X_train = [text.lower() for text in cleaned_X_train]

## Now let's work on removing stopwords
Remove the stopwords.

In [36]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
for text in cleaned_X_train:
    words = [word for word in text.split() if word not in stop_words]
    cleaned_text = " ".join(words)
    cleaned_X_train = [" ".join([word for word in text.split() if word not in stop_words]) for text in cleaned_X_train]

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [39]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
for text in cleaned_X_train:
    words = [lemmatizer.lemmatize(word) for word in text.split()]
    cleaned_text = " ".join(words)
    cleaned_X_train = [" ".join([lemmatizer.lemmatize(word) for word in text.split()]) for text in cleaned_X_train]

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(cleaned_X_train)

## Extra features

In [47]:
data_train = pd.DataFrame({
    "preprocessed_text": cleaned_X_train
})

data_val = pd.DataFrame({
    "preprocessed_text": X_test.reset_index(drop=True)
})
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x))

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x))

data_train.head()

,preprocessed_text,money_mark,suspicious_words,text_len
0,ready pls call ops connect blair,0,0,32
1,fromamrekabir belloe emaila kabirsheecomtelaea...,0,1,1503
2,ok let mcguinness gate ffasi probably office e...,0,0,67
3,doc strategic dialogue press clip march doc st...,0,0,311
4,froma mre hoffman bancoleyaccrac ghanaeattn ai...,1,1,944

## How would work the Bag of Words with Count Vectorizer concept?

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
X_bow = vectorizer.fit_transform(cleaned_X_train)
print(X_bow.shape)

(800, 16180)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [56]:
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(cleaned_X_train)
print(X_tfidf.shape)

(800, 16180)

## And the Train a Classifier?

In [63]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_tfidf, y_train)

MultinomialNB()

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code